'use strict';

const fs = require('fs');

const BoomParser = require('./BoomParser');

const [
	Linedef,
	Sector,
	Thing,
	Sidedef,
	Vertex
] = [
	require('./structures/linedef'),
	require('./structures/sector'),
	require('./structures/thing'),
	require('./structures/sidedef'),
	require('./structures/vertex')
];

const VERTEXES = 'input/VERTEXES.lmp';
const LINEDEFS = 'input/LINEDEFS.lmp';
const SECTORS = 'input/SECTORS.lmp';
const THINGS = 'input/THINGS.lmp';
const SIDEDEFS = 'input/SIDEDEFS.lmp';

const TEXTMAP = 'output/TEXTMAP';

function parseVertexes() {
	const vertexes = BoomParser.getVertexes(VERTEXES);

	const out = [];

	for (const i in vertexes) {
		const vertex = vertexes[i];

		out.push(new Vertex(i, vertex.x, vertex.y));
	}

	let outstring = '// Vertexes\n';

	for (const vertex of out) {
		console.log(vertex.toString());
		outstring += vertex.toString();
	}

	return outstring;
}

function parseThings() {
	const things = BoomParser.getThings(THINGS);

	const out = [];

	for (const i in things) {
		const thing = things[i];

		out.push(new Thing(i, thing.x, thing.y, thing.angle, thing.tid, thing.flags));
	}

	let outstring = '// Things\n';

	for (const thing of out) {
		console.log(thing.toString());
		outstring += thing.toString();
	}

	return outstring;
}

function parseSectors() {
	const sectors = BoomParser.getSectors(SECTORS);

	const out = [];

	for (const i in sectors) {
		const sector = sectors[i];

		out.push(new Sector(i, sector.floor, sector.height, sector.floortex, sector.ceiltex, sector.light, sector.special, sector.tag));
	}

	let outstring = '// Sectors\n';

	for (const sector of out) {
		console.log(sector.toString());
		outstring += sector.toString();
	}

	return outstring;
}

function parseLinedefs() {
	const linedefs = BoomParser.getLinedefs(LINEDEFS);

	const out = [];

	for (const i in linedefs) {
		const linedef = linedefs[i];

		out.push(new Linedef(i, linedef.v1, linedef.v2, linedef.flags, linedef.action, linedef.tag, linedef.front, linedef.back));
	}

	let outstring = '// LineDefs\n';

	for (const linedef of out) {
		console.log(linedef.toString());
		outstring += linedef.toString();
	}

	return outstring;
}

function parseSidedefs() {
	const sidedefs = BoomParser.getSides(SIDEDEFS);

	const out = [];

	for (const i in sidedefs) {
		const sidedef = sidedefs[i];

		out.push(new Sidedef(i, sidedef.offsetx, sidedef.offsety, sidedef.uppertex, sidedef.lowertex, sidedef.middletex, sidedef.sector));
	}

	let outstring = '// SideDefs\n';

	for (const sidedef of out) {
		console.log(sidedef.toString());
		outstring += sidedef.toString();
	}

	return outstring;
}

let output = '// Generated by Boom2UDMF ©PROPHESSOR 2018\n\n';

output += parseThings();
output += parseVertexes();
output += parseLinedefs();
output += parseSidedefs();
output += parseSectors();
output += '\n\n// End of file';

fs.writeFileSync(TEXTMAP, output, 'utf8');